server:
  port: 8388

spring:
  application:
    name: luck-shutdown

logging:
  level:
    com.lqh.dev.mapper: debug

endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  security:
    enabled: true
    roles: ADMIN
  context-path: /actuator
  port: 7388
security:
  user:
    name: admin
    password: admin
